# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Install UPX
      run: |
        sudo apt update && sudo apt install -y upx

    - name: Compress executable
      run: upx --best patchsplit

    - name: Make the binary executable
      run: chmod +x patchsplit

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: patchsplit
        path: patchsplit
